### ISSUE TITLE
app crashed when discord isn't opened

### ISSUE THREAD

**Issue by rickmartensnl** [jagrosh/DiscordIPC#12]
How to fix it that the app crashes when discord isn't opened?

`IPCClient client = new IPCClient(/*ID not for you*/);
			client.setListener(new IPCListener() {
				private Minecraft mc;

				@Override
				public void onReady(IPCClient client) {
					RichPresence.Builder builder = new RichPresence.Builder();
					builder.setState("Versie: " + getMinecraft().getVersion())
							.setDetails("Naam: " + getMinecraft().getSession().getUsername())
							.setStartTimestamp(OffsetDateTime.now())
							.setLargeImage("monkey-logo", "Client Side Anicheat");
					client.sendRichPresence(builder.build());
				}
			});
			try {
				client.connect();
			} catch (NoDiscordClientException e) {
				e.printStackTrace();
			}`

**Comment by rickmartensnl** [comment]
something went wrong with copying
`IPCClient client = new IPCClient(468063053829898250L);
			client.setListener(new IPCListener() {
				private Minecraft mc;

				@Override
				public void onReady(IPCClient client) {
					RichPresence.Builder builder = new RichPresence.Builder();
					builder.setState("Versie: " + getMinecraft().getVersion())
							.setDetails("Naam: " + getMinecraft().getSession().getUsername())
							.setStartTimestamp(OffsetDateTime.now())
							.setLargeImage("monkey-logo", "Client Side Anicheat");
					client.sendRichPresence(builder.build());
				}
			});
			try {
				client.connect();
			} catch (NoDiscordClientException e) {
				e.printStackTrace();
			}`

**Comment by rickmartensnl** [comment]
IPCClient client = new IPCClient(468063053829898250L);
			client.setListener(new IPCListener() {
				private Minecraft mc;

				@Override
				public void onReady(IPCClient client) {
					RichPresence.Builder builder = new RichPresence.Builder();
					builder.setState("Versie: " + getMinecraft().getVersion())
							.setDetails("Naam: " + getMinecraft().getSession().getUsername())
							.setStartTimestamp(OffsetDateTime.now())
							.setLargeImage("monkey-logo", "Client Side Anicheat");
					client.sendRichPresence(builder.build());
				}
			});
			try {
				client.connect();
			} catch (NoDiscordClientException e) {
				e.printStackTrace();
			}

**Comment by jagrosh** [comment]
Please provide debug logs of the exception, as well as a hastebin or link to the full code if possible.

**Comment by rickmartensnl** [comment]
java.lang.RuntimeException: org.newsclub.net.unix.AFUNIXSocketException: Connection refused (socket: /private/var/folders/s8/gdj6mr5x6zx0nhdnl35gvcs40000gp/T/discord-ipc-0)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:167)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at net.minecrafthydra.HydraClient.RunDiscordRPC(HydraClient.java:53)
	at net.minecrafthydra.HydraClient.StartClient(HydraClient.java:26)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:564)
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Connection refused (socket: /private/var/folders/s8/gdj6mr5x6zx0nhdnl35gvcs40000gp/T/discord-ipc-0)
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:136)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:107)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:98)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:46)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:167)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at net.minecrafthydra.HydraClient.RunDiscordRPC(HydraClient.java:53)
	at net.minecrafthydra.HydraClient.StartClient(HydraClient.java:26)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:564)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)
