### ISSUE TITLE
Error while closing the stream in IPCClient#close

### ISSUE THREAD

**Issue by iHDeveloper** [jagrosh/DiscordIPC#14]
Hello @jagrosh 

I'm receiving while calling the function `IPCClient#close` which it should close everything safety but it appears an exception that I can't handle it by try and catch because it's in a different thread. So, I hope there's a solution for this error.

```
21:25:26.238 [Thread-11] ERROR com.jagrosh.discordipc.IPCClient - Reading thread encountered an IOException
java.io.IOException: Stream Closed
    at java.io.RandomAccessFile.length(Native Method)
    at com.jagrosh.discordipc.entities.pipe.WindowsPipe.read(WindowsPipe.java:56)
    at com.jagrosh.discordipc.IPCClient.lambda$startReading$0(IPCClient.java:350)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by iHDeveloper** [comment]
Well, Could we have a way to disable the error from the logger like `setLogLevel`. It will be useful to just let the `IPCClient` log whatever we want for having a useful log. 😄

**Comment by jagrosh** [comment]
IPCClient doesn't impose any particular logging dependency on you, it utilizes SLF4J, so you already can set the logging level to whatever you wish using your logging dependency

**Comment by iHDeveloper** [comment]
Thanks, @jagrosh for helping me. I appreciate it 😄
