### ISSUE TITLE
Issue from Skyhanni

### ISSUE THREAD

**Issue by MaXKX11** [jagrosh/DiscordIPC#33]
idk what this means but skyhanni told me to report it in the sh dc so i searched for it in the settings and it brought me here
```
SkyHanni 0.27.Beta.12: Caught an IllegalStateException in HoppityEggsManager at LorenzChatEvent: Unknown meal: Brunch
 
Caused by java.lang.IllegalStateException: Unknown meal: Brunch
	at SH.test.command.ErrorManager.skyHanniError(ErrorManager.kt:62)
	at SH.features.event.hoppity.HoppityEggsManager.getEggType$1_8_9(HoppityEggsManager.kt:174)
	at SH.features.event.hoppity.HoppityEggsManager.onChat(HoppityEggsManager.kt:167)
	at SH.data.ChatManager.onChatReceive(ChatManager.kt:130)
	at FML.common.eventhandler.EventBus.post(EventBus.java:140)
```

**Comment by not-a-cowfr** [comment]
1. update your [neu](https://github.com/NotEnoughUpdates/NotEnoughUpdates/releases/latest) and [skyhanni](https://github.com/hannibal002/SkyHanni/releases/latest)
2. skyhanni literally told you to get [support](https://discord.com/channels/997079228510117908/1000669238035497022) in the discord, not on the discordIPC github
